# Generated by Django 5.2.5 on 2025-12-19 13:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner'),
        ),
    ]
